### PR TITLE
testing github actions.

### PR DESCRIPTION
**Pull request by jakejh**

### CODE REVIEW

**Comment by jakejh** [comment]
Let's go ahead and remove the .circleci folder from this branch as well, to avoid sending twice to codecov and drat.

**Comment by jakejh** [comment]
A few things I'm thinking about, you may be ahead of me here.

1. What's the best way to make drat-deployment dependent on the R-CMD-check and test-coverage actions succeeding? Maybe `needs` [here](https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows#creating-dependent-jobs)?
2. Do we want R-CMD-check, test-coverage, and drat-deployment as separate workflows or separate jobs within a workflow? R-CMD-check and test-coverage will run on every branch, but drat-deployment will only run on pushes to master or main.
3. Until we're sure it's working, let's create a drat_test repo for the action to pull from and push to.

**Comment by JSchoenbachler** [comment]
I will remove circleci soon, still using the config as a reference in my testing.

Other comment response:
1. I was thinking we could use multiple jobs, but I will need to check and make sure there isn't a way to do this using workflows. I can appreciate having these in separate workflows, but doing it using jobs would also be easy (and simplify the setup steps).
2. See above. We could go that path, but also I could just keep a check for if it is master or main like in the circleci config.
3. do you mean just a drat_test repo that is a clone of the current drat repo?

**Comment by JSchoenbachler** [comment]
@jakejh to be a little more strongly opinionated, I think the best way to go about this would be to use the multiple jobs in a single workflow method.

I found a solution here to use the `workflow_run` syntax for depending on multiple workflows: https://stackoverflow.com/questions/58457140/dependencies-between-workflows-on-github-actions

However, I still think just keeping everything in one single workflow will make things go more smoothly. It will be less complex to specify `needs` between jobs than it will be to specify the other workflows and additionally depend on the outcome of them (which is separate in itself). It will also keep all things to one file, making it easier to set up and configure a repository without adding multiple files to manage.

**Comment by JSchoenbachler** [comment]
Going to do a merge to test something quickly.

**Comment by jakejh** [comment]
I'm fine with having separate jobs within one workflow. You're clearly on top of things.

**Pull request merged**
